SIZE = 40
GAME_WIDTH = 1000
GAME_HEIGHT = 600
BACKGROUND_COLOR = (110, 110, 5)
SNAKE_INITIAL_SIZE = 10

X_STEP_INCREMENT = GAME_WIDTH / SIZE
Y_STEP_INCREMENT = GAME_HEIGHT / SIZE

SCORE_FONT_SIZE = GAME_HEIGHT // 20
SCORE_X = GAME_WIDTH // 1.25
SCORE_Y = GAME_HEIGHT // 60
SCORE_FONT_COLOR = (200, 200, 200)

GAME_OVER_FONT_SIZE = GAME_HEIGHT // 20
GAME_OVER_X = GAME_WIDTH // 5
GAME_OVER_Y = GAME_HEIGHT // 3
GAME_OVER_XY = (GAME_OVER_X, GAME_OVER_Y)
PLAY_AGAIN_XY = (GAME_OVER_X, GAME_OVER_Y + GAME_OVER_FONT_SIZE // 0.6)
